name: Build VyOS Circinus

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout VyOS Build Repository
        uses: actions/checkout@v4
        with:
          repository: vyos/vyos-build
          ref: current
          
      - name: Build VyOS Docker Builder
        run: docker build -t vyos-builder docker
        
      - name: Compile VyOS ISO
        run: |
          docker run --rm --privileged -v ${{ github.workspace }}:/vyos -w /vyos vyos-builder \
          bash -c "sudo ./build-vyos-image generic --architecture amd64 --build-by 'GitHub-Actions'"
          
      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VyOS-Circinus-amd64
          path: build/*.iso
          retention-days: 3
